version: '2'

services:

  client:
      image: node:8
      command: bash -c "cd /app && yarn install && yarn run start:docker:poll"
      volumes:
          - ./:/app
      ports:
          - "4200:4200"
