version: '3'
services:
  angular_app:
    image: node:8.16.0-alpine
    container_name: 'angular_app'
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    ports:
      - '4200:4200'
    command: >
      /bin/sh -c "yarn install && yarn run start:docker:poll"
